/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.timesheet.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.timesheet.model.Day;
import com.liferay.timesheet.service.DayLocalServiceUtil;

/**
 * The extended model base implementation for the Day service. Represents a row in the &quot;timesheet_Day&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DayImpl}.
 * </p>
 *
 * @author Istvan Sajtos, Zsolt Szabo
 * @see DayImpl
 * @see com.liferay.timesheet.model.Day
 * @generated
 */
public abstract class DayBaseImpl extends DayModelImpl implements Day {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a day model instance should use the {@link Day} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			DayLocalServiceUtil.addDay(this);
		}
		else {
			DayLocalServiceUtil.updateDay(this);
		}
	}
}