/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.timesheet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Day service. Represents a row in the &quot;timesheet_Day&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.timesheet.model.impl.DayModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.timesheet.model.impl.DayImpl}.
 * </p>
 *
 * @author Istvan Sajtos, Zsolt Szabo
 * @see Day
 * @see com.liferay.timesheet.model.impl.DayImpl
 * @see com.liferay.timesheet.model.impl.DayModelImpl
 * @generated
 */
public interface DayModel extends BaseModel<Day>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a day model instance should use the {@link Day} interface instead.
	 */

	/**
	 * Returns the primary key of this day.
	 *
	 * @return the primary key of this day
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this day.
	 *
	 * @param primaryKey the primary key of this day
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the day ID of this day.
	 *
	 * @return the day ID of this day
	 */
	public long getDayId();

	/**
	 * Sets the day ID of this day.
	 *
	 * @param dayId the day ID of this day
	 */
	public void setDayId(long dayId);

	/**
	 * Returns the group ID of this day.
	 *
	 * @return the group ID of this day
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this day.
	 *
	 * @param groupId the group ID of this day
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this day.
	 *
	 * @return the company ID of this day
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this day.
	 *
	 * @param companyId the company ID of this day
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this day.
	 *
	 * @return the user ID of this day
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this day.
	 *
	 * @param userId the user ID of this day
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this day.
	 *
	 * @return the user uuid of this day
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this day.
	 *
	 * @param userUuid the user uuid of this day
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this day.
	 *
	 * @return the user name of this day
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this day.
	 *
	 * @param userName the user name of this day
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this day.
	 *
	 * @return the create date of this day
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this day.
	 *
	 * @param createDate the create date of this day
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this day.
	 *
	 * @return the modified date of this day
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this day.
	 *
	 * @param modifiedDate the modified date of this day
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the date of this day.
	 *
	 * @return the date of this day
	 */
	public Date getDate();

	/**
	 * Sets the date of this day.
	 *
	 * @param date the date of this day
	 */
	public void setDate(Date date);

	/**
	 * Returns the type of this day.
	 *
	 * @return the type of this day
	 */
	public int getType();

	/**
	 * Sets the type of this day.
	 *
	 * @param type the type of this day
	 */
	public void setType(int type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Day day);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Day> toCacheModel();

	@Override
	public Day toEscapedModel();

	@Override
	public Day toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}