/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.timesheet.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TaskSession service. Represents a row in the &quot;timesheet_TaskSession&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.timesheet.model.impl.TaskSessionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.timesheet.model.impl.TaskSessionImpl}.
 * </p>
 *
 * @author Istvan Sajtos, Zsolt Szabo
 * @see TaskSession
 * @see com.liferay.timesheet.model.impl.TaskSessionImpl
 * @see com.liferay.timesheet.model.impl.TaskSessionModelImpl
 * @generated
 */
public interface TaskSessionModel extends BaseModel<TaskSession> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task session model instance should use the {@link TaskSession} interface instead.
	 */

	/**
	 * Returns the primary key of this task session.
	 *
	 * @return the primary key of this task session
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task session.
	 *
	 * @param primaryKey the primary key of this task session
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the task session ID of this task session.
	 *
	 * @return the task session ID of this task session
	 */
	public long getTaskSessionId();

	/**
	 * Sets the task session ID of this task session.
	 *
	 * @param taskSessionId the task session ID of this task session
	 */
	public void setTaskSessionId(long taskSessionId);

	/**
	 * Returns the create date of this task session.
	 *
	 * @return the create date of this task session
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this task session.
	 *
	 * @param createDate the create date of this task session
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this task session.
	 *
	 * @return the modified date of this task session
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this task session.
	 *
	 * @param modifiedDate the modified date of this task session
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this task session.
	 *
	 * @return the user ID of this task session
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this task session.
	 *
	 * @param userId the user ID of this task session
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this task session.
	 *
	 * @return the user uuid of this task session
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this task session.
	 *
	 * @param userUuid the user uuid of this task session
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the end time of this task session.
	 *
	 * @return the end time of this task session
	 */
	public Date getEndTime();

	/**
	 * Sets the end time of this task session.
	 *
	 * @param endTime the end time of this task session
	 */
	public void setEndTime(Date endTime);

	/**
	 * Returns the start time of this task session.
	 *
	 * @return the start time of this task session
	 */
	public Date getStartTime();

	/**
	 * Sets the start time of this task session.
	 *
	 * @param startTime the start time of this task session
	 */
	public void setStartTime(Date startTime);

	/**
	 * Returns the task ID of this task session.
	 *
	 * @return the task ID of this task session
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this task session.
	 *
	 * @param taskId the task ID of this task session
	 */
	public void setTaskId(long taskId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TaskSession taskSession);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TaskSession> toCacheModel();

	@Override
	public TaskSession toEscapedModel();

	@Override
	public TaskSession toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}