/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.timesheet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Task service. Represents a row in the &quot;timesheet_Task&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.timesheet.model.impl.TaskModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.timesheet.model.impl.TaskImpl}.
 * </p>
 *
 * @author Istvan Sajtos, Zsolt Szabo
 * @see Task
 * @see com.liferay.timesheet.model.impl.TaskImpl
 * @see com.liferay.timesheet.model.impl.TaskModelImpl
 * @generated
 */
public interface TaskModel extends BaseModel<Task> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task model instance should use the {@link Task} interface instead.
	 */

	/**
	 * Returns the primary key of this task.
	 *
	 * @return the primary key of this task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task.
	 *
	 * @param primaryKey the primary key of this task
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the task ID of this task.
	 *
	 * @return the task ID of this task
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this task.
	 *
	 * @param taskId the task ID of this task
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the company ID of this task.
	 *
	 * @return the company ID of this task
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this task.
	 *
	 * @param companyId the company ID of this task
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this task.
	 *
	 * @return the create date of this task
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this task.
	 *
	 * @param createDate the create date of this task
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the creator ID of this task.
	 *
	 * @return the creator ID of this task
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this task.
	 *
	 * @param creatorId the creator ID of this task
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the task name of this task.
	 *
	 * @return the task name of this task
	 */
	@AutoEscape
	public String getTaskName();

	/**
	 * Sets the task name of this task.
	 *
	 * @param taskName the task name of this task
	 */
	public void setTaskName(String taskName);

	/**
	 * Returns the project ID of this task.
	 *
	 * @return the project ID of this task
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this task.
	 *
	 * @param projectId the project ID of this task
	 */
	public void setProjectId(long projectId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Task task);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Task> toCacheModel();

	@Override
	public Task toEscapedModel();

	@Override
	public Task toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}